In [ ]:
# Abbiamo una lista di liste#

In [3]:
mat = [[0,1,2,3,4] , [5,6,7,8,9], [10,11,12,13,14]]

import numpy
#che tipo di struttura dati o matematica potrebbe rappresentare? #
#è una matrice ...#

In [5]:
mat

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

In [9]:
elem=mat[1][2] #creo una variabile dove indico nella prima [..] la posizione della lista e nella seconda [] la posizione #
elem           #dell'elemento #

7

In [4]:
#Importiamo il modulo math e proviamo a usare le funzioni #
# sin()
# cos()
# factorial()

In [13]:
import math

In [14]:
math.sin (60)

-0.3048106211022167

In [15]:
math.cos(184)

-0.21513470736462095

In [10]:
math.factorial(5) #5*4*3*2*1#

120

In [17]:
math.pi  # pi è il pi greco =3.14....# 

3.141592653589793

In [16]:
math.degrees(math.pi) # il metodo degrees ==>  gradi=angolo(radianti) * 180/ pigreco
                      # essendo pi greco la misura in radianti dell'angolo il risultato è 180

180.0

In [22]:
math.degrees(4.2)

240.64227395494578

In [ ]:
#L'azienda Object Spa ha creato una lista di quanti oggetti ha venduto ogni mese nell'ultimo anno : #

In [2]:
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]

In [3]:
import numpy
lst_npy= numpy.array(lst)

In [4]:
lst_npy

array([2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100,
       5350])

In [8]:
a=lst_npy.max()
print(f'La vendita maggiore è stata di : {a}')

La vendita maggiore è stata di : 8150


In [10]:
b=lst_npy.min()
print(f'La vendita minore è stata di : {b}')

La vendita minore è stata di : 1280


In [18]:
c=lst_npy>4999 #Quali sono state le vendite maggiori a 4999 oggetti#
lst_npy[c]

array([5500, 7200, 6410, 8150, 7100, 5350])

In [25]:
c.sum()  #somma i singoli valori boleani restituendo il numero dei boleani e quindi il totale dei valori superiori a 4999#

6

In [26]:
d=lst_npy<3000 #Quali sono state le vendite minori a 3000 oggetti#
lst_npy[d]

array([2000, 1280, 1900, 2500])

In [27]:
d.sum()

4

In [32]:
x=lst_npy.sum()/(c+d).sum()
print(f'La Media del numero di oggetti venduti al mese è : {x}') 

La Media del numero di oggetti venduti al mese è : 5561.0


In [ ]:
#Consideriamo il seguente dizionario ... #

In [38]:
import pandas as pd
fatturati_dict = {1997 : 12_000, 1998 : 15_000,
                  1999 : 20_000, 2000 : 23_000,
                  2001 : 25_000, 2022 : 17_000,
                  2003 : 14_000, 2004 : 21_000}

In [39]:
#Consideriamo la seguenteSeries ... :#

In [40]:
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000],
                             index=range(1997,2005))

In [41]:
fatturati_dict

{1997: 12000,
 1998: 15000,
 1999: 20000,
 2000: 23000,
 2001: 25000,
 2022: 17000,
 2003: 14000,
 2004: 21000}

In [42]:
fatturati_series

1997    12000
1998    15000
1999    20000
2000    23000
2001    25000
2002    17000
2003    14000
2004    21000
dtype: int64

In [ ]:
fatturati_dict

In [44]:
fatturati_series.get(1997) #Per il dizionario devo utilizzare l'attributo get e specificare la chiave...#

12000

In [46]:
fatturati_series[1997] #Per le Series basta indicare l'etichetta della Series per avere il corrispondente valore#

12000

In [49]:
print (fatturati_series + 5) #Posso fare operazioni in modo vettoriale grazie al Masking ...#

1997    12005
1998    15005
1999    20005
2000    23005
2001    25005
2002    17005
2003    14005
2004    21005
dtype: int64


In [ ]:
# L'azienda Object Spa ha un dataset con tutti gli stipendi dei dipendenti memorizzato in un ndarray :#

In [50]:
import numpy as np

In [51]:
stipendi = np.array([100,200,300,400,500,600,700,800,900,1000])

In [55]:
stipendio=0
stip_radd=[]
for x in stipendi:
    y=x*2
    stip_radd.append(y)
print(f' Gli stipendi raddoppiati sono : {stip_radd}')
    

 Gli stipendi raddoppiati sono : [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]


In [56]:
stip_radd2=stipendi*2
stip_radd2

array([ 200,  400,  600,  800, 1000, 1200, 1400, 1600, 1800, 2000])